[[plugins]]
package = "."

  [plugins.inputs]
  skipTests = true
  extraLogging = true
  skipStatusUpdate = true

[[plugins]]
package = "@netlify/plugin-local-install-core"

[build]
  command = "echo onBuild"

[context.test.environment]
  GITHUB_PERSONAL_TOKEN = "notreal"